---
title: "State of the Union Sentiment Analysis"
author: "Jack Schroeder"
date: "10/29/2018"
output: html_document
---

```{r setup, include=FALSE,echo=FALSE,message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(readr)
library(stringr)
library(lubridate)
library(quanteda)
library(DT)
library(tidytext)
library(tidyr)
```

```{r,echo=FALSE,message=FALSE,warning=FALSE}
sou <- read_csv("data/sou.csv")
presidents <- read_csv("data/presidents.csv")

sou <- sou %>%
  left_join(presidents)

afinn<- get_sentiments("afinn")

tidy_sou<-sou %>% 
  unnest_tokens(word,text) %>% 
  inner_join(afinn, by = "word")

positivity<- tidy_sou %>% 
  group_by(president,date) %>% 
  summarize(wordScore = mean(score)) %>% 
  arrange(desc(wordScore)) %>% 
  left_join(sou, by = "president")

ggplot(positivity,aes(x=date.x,y=wordScore,color=party)) +
  geom_point() +
  ggtitle("State of the Union Addresses Got Sad During the War.", subtitle = "Also After 9/11.") +
  xlab("Date") +
  ylab("Positivity Score of Speech")


```

